"""Generate the manual verification checklist.

Automated round-trip validation proves the file is self-consistent. It cannot
prove Media Composer will open it, relink it, and put the right frame in the
right place — only Media Composer can prove that.

This writes the exact expected values, per clip, so checking is reading numbers
off a screen rather than forming an opinion.
"""

from __future__ import annotations

from pathlib import Path

import opentimelineio as otio

from rates import Rate
from timecode import frames_to_tc as format_tc


def write(timeline: otio.schema.Timeline, rate: Rate, media: Path,
          out_path: Path, export_summary: str) -> Path:
    v_track = next(t for t in timeline.tracks
                   if t.kind == otio.schema.TrackKind.Video)
    clips = list(v_track.find_clips())
    rec = round(timeline.global_start_time.value)

    rows = []
    for i, clip in enumerate(clips):
        sr = clip.source_range
        s_in = round(sr.start_time.value)
        dur = round(sr.duration.value)
        meta = clip.metadata.get("mishne", {})
        rows.append(
            f"| {i + 1} | `{format_tc(s_in, rate)}` | `{format_tc(s_in + dur, rate)}` "
            f"| `{format_tc(rec, rate)}` | {dur} | {meta.get('why', '')} |"
        )
        rec += dur

    total = rec - round(timeline.global_start_time.value)

    out_path.write_text(f"""# Verification checklist — {rate.label}

Generated by the Spike A tool. Source media: `{media.name}`

- Edit rate: **{rate.num}/{rate.den}** ({rate.fps:.3f} fps){", **drop-frame**" if rate.drop_frame else ""}
- Source start timecode: **{format_tc(round(clips[0].media_reference.available_range.start_time.value), rate)}**
- Record start timecode: **{format_tc(round(timeline.global_start_time.value), rate)}**
- Clips: **{len(clips)}** · total duration **{total} frames** ({total / rate.fps:.2f}s)

## Export results

{export_summary}

## How to check

The test media has its own timecode burned into every frame and a 1 kHz blip on
every second boundary. That means you do not have to trust anything: park on the
first frame of a clip and read the number off the picture.

For each NLE:

1. Import the file below.
2. Confirm the media relinks. Note whether it relinked **silently** or asked you
   to locate the file — silent relink is the pass condition, since that is what
   a customer gets.
3. For each row in the table, park on the clip's first frame and read the
   burned-in timecode. **It must equal the Source In column.**
4. Check the last frame against Source Out.
5. Confirm the clip count matches and no clips merged.
6. Scrub the audio: blips must sit on second boundaries, in sync, at the end of
   the sequence as well as the start.
7. Trim a clip's head. Handles are 6 frames — you should have room to trim both
   ways on every clip that is not at the media boundary.

| File | Open in |
|---|---|
| `{rate.key}.aaf` | Avid Media Composer |
| `{rate.key}.fcpxml` | Premiere Pro, DaVinci Resolve, Final Cut Pro |
| `{rate.key}.edl` | Anything — lowest fidelity, tests timecode only |

## Expected values

Source In and Source Out **include handles** — that is what the file contains,
and it is what the NLE will show you.

| # | Source In | Source Out | Record In | Frames | What this row is testing |
|---|---|---|---|---|---|
{chr(10).join(rows)}

## Result

Fill this in. A blank checklist proves nothing.

| NLE | Opens | Relinks silently | TC exact | Count | Sync at tail | Handles |
|---|---|---|---|---|---|---|
| Avid Media Composer | | | | | | |
| Premiere Pro | | | | | | |
| DaVinci Resolve | | | | | | |
| Final Cut Pro | | | | | | |

Notes:
""")
    return out_path
